server:
  port: 8081

cloud:
  aws:
    region:
      static: eu-central-1
      auto: false
    credentials:
      access-key: AKIAZLSCHF3AJTVUQOHX
      secret-key: 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
    end-point:
      uri: https://sqs.eu-central-1.amazonaws.com/643310235328/gun-photo-queue

spring:
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration
  datasource:
    url: jdbc:postgresql://${DB_SERVER}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    #url: jdbc:postgresql://localhost/guns
    #username: postgres
    #password: 1
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

model:
  #url: http://gun-detector-model:8000/
  #detect_endpoint: /detect
  url: http://${MODEL_HOST}:${MODEL_PORT}
  detect_endpoint: /${MODEL_DETECT_ENDPOINT}